object ModernMessageForm: TModernMessageForm
  Left = 0
  Top = 0
  Caption = 'ModernMessageForm'
  ClientHeight = 200
  ClientWidth = 400
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  Position = poScreenCenter
  OnCreate = FormCreate
  OnKeyDown = FormKeyDown
  OnPaint = FormPaint
  OnResize = FormResize
  OnShow = FormShow
  TextHeight = 13
  object lblTitle: TLabel
    Left = 59
    Top = 23
    Width = 35
    Height = 16
    Caption = 'Titulo'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object imgIcon: TImage
    Left = 19
    Top = 19
    Width = 32
    Height = 32
    Transparent = True
  end
  object shpOK: TShape
    Left = 307
    Top = 153
    Width = 75
    Height = 30
    Shape = stRoundRect
    OnMouseDown = shpOKMouseDown
    OnMouseEnter = shpOKMouseEnter
    OnMouseLeave = shpOKMouseLeave
  end
  object lblOK: TLabel
    Left = 307
    Top = 158
    Width = 17
    Height = 16
    Caption = 'OK'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    OnClick = shpOKClick
    OnMouseEnter = shpOKMouseEnter
    OnMouseLeave = shpOKMouseLeave
  end
  object shpCancel: TShape
    Left = 226
    Top = 153
    Width = 75
    Height = 30
    Shape = stRoundRect
    OnMouseDown = shpCancelMouseDown
    OnMouseEnter = shpCancelMouseEnter
    OnMouseLeave = shpCancelMouseLeave
  end
  object lblCancel: TLabel
    Left = 240
    Top = 158
    Width = 50
    Height = 16
    Caption = 'Cancelar'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    OnClick = shpCancelClick
    OnMouseEnter = shpCancelMouseEnter
    OnMouseLeave = shpCancelMouseLeave
  end
  object shpYes: TShape
    Left = 307
    Top = 153
    Width = 75
    Height = 30
    Shape = stRoundRect
    OnMouseDown = shpYesMouseDown
    OnMouseEnter = shpYesMouseEnter
    OnMouseLeave = shpYesMouseLeave
  end
  object lblYes: TLabel
    Left = 331
    Top = 158
    Width = 22
    Height = 16
    Caption = 'Sim'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    OnClick = shpYesClick
    OnMouseEnter = shpYesMouseEnter
    OnMouseLeave = shpYesMouseLeave
  end
  object shpNo: TShape
    Left = 226
    Top = 153
    Width = 75
    Height = 30
    Shape = stRoundRect
    OnMouseDown = shpNoMouseDown
    OnMouseEnter = shpNoMouseEnter
    OnMouseLeave = shpNoMouseLeave
  end
  object lblNo: TLabel
    Left = 253
    Top = 158
    Width = 22
    Height = 16
    Caption = 'N'#227'o'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    OnClick = shpNoClick
    OnMouseEnter = shpNoMouseEnter
    OnMouseLeave = shpNoMouseLeave
  end
  object scrBody: TScrollBox
    Left = 6
    Top = 66
    Width = 388
    Height = 81
    BorderStyle = bsNone
    TabOrder = 0
    object lblText: TLabel
      Left = 13
      Top = 13
      Width = 97
      Height = 13
      Caption = 'Texto da mensagem'
      WordWrap = True
    end
  end
end
